accounts/urls.py
from django.urls import path
from .views import UserLoginView, register_view

app_name = 'accounts'

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('register/', register_view, name='register'),
]

item_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('lists', include('lists.urls')),
]

lists/urls.py
from django.urls import path
from . import views

app_name = 'lists'

urlpatterns = [
    path('', views.list_index, name='list_index'),
    #path('<int:list_id>/edit/', views.list_edit, name='list_edit'),
    #path('<int:list_id>/delete/', views.list_delete, name='list_delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

lists/models.py
from django.db import models
from django.conf import settings


class List(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="lists",
    )
    title = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Item(models.Model):
    packing_list = models.ForeignKey(
        List,
        on_delete=models.CASCADE,
        related_name="items",
    )
    name = models.CharField(max_length=30)
    memo = models.CharField(max_length=40, blank=True)
    is_checked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

lists/forms.py
from django import forms
from .models import List


class Listform(forms.ModelForm):
    class Meta:
        model = List
        fields = ["title"]
        widgets = {
            "title": forms.TimeInput(attrs={
                "placeholder": "例：沖縄旅行",
                "maxlength": 20,
            })
        }
        error_messages = {
            "title": {
                "required": "タイトルを入力してください",
                "max_length": "タイトルは20文字以内で入力してください",
            }
        }

accounts/views.py
#ログインビューのクラスを継承するため
from django.contrib.auth.views import LoginView
#画面再表示・遷移に必要
from django.shortcuts import render, redirect
#ユーザーテーブル
from django.contrib.auth.models import User
#自動ログインに必要
from django.contrib.auth import authenticate, login

#ログイン画面
class UserLoginView(LoginView):
    template_name = 'accounts/login.html'


#アカウント登録画面
def register_view(request):
    if request.method == "POST":
        username = request.POST.get("username", "").strip()
        email = request.POST.get("email", "").strip()
        password1 = request.POST.get("password1", "")
        password2 = request.POST.get("password2", "")

        errors = {}

        if not username:
            errors.setdefault("username", []).append("ユーザー名を入力してください")
        else:
            if not (1 <= len(username) <= 20):
                errors.setdefault("username", []).append("ユーザー名は１文字～２０文字で入力してください")
            if User.objects.filter(username=username).exists():
                errors.setdefault("username", []).append("このユーザーは既に使われています")

        if not email:
            errors.setdefault("email", []).append("メールアドレスを入力してください")
        else:
            if User.objects.filter(email=email).exists():
                errors.setdefault("email", []).append("このメールアドレスは既に使われています")

        if not password1:
            errors.setdefault("password1", []).append("パスワードを入力してください")
        else:
            if len(password1) < 8:
                errors.setdefault("password1", []).append("パスワードは８文字以上に入力してください")
            has_letter = any(char.isalpha() for char in password1)
            has_number = any(char.isdigit() for char in password1)
            if not (has_letter and has_number):
                errors.setdefault("password1", []).append("パスワードは英字と数字の両方を含めてください")

        if not password2:
            errors.setdefault("password2", []).append("確認用パスワードを入力してください")
        else:
            if password1 and password1 != password2:
                errors.setdefault("password2", []).append("パスワードが一致しません")
        
        #エラー時に入力内容保持する（パスワード以外）
        if errors:
            return render(
                request,
                "accounts/register.html",
                {
                    "errors": errors,
                    "username": username,
                    "email": email,
                }
            )

        #ここでユーザーテーブルのカラムの中身を追加
        User.objects.create_user(
            username=username,
            email=email,
            password=password1
        )

        user = authenticate(username=username, password=password1)

        #エラー時に入力内容保持する（パスワード以外）
        if user is None:
            errors.append("ログイン処理に失敗しました もう一度お試しください")
            return render(
                request,
                "accounts/register.html",
                {
                    "errors": errors,
                    "username": username,
                    "email": email,
                }
            )
        login(request, user)

        return redirect("lists:list_index")
    return render(request, "accounts/register.html")

lists/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import List
from .forms import Listform


@login_required
def list_index(request):
    if request.method == "POST":
        form = Listform(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect("lists/list_index")
    else:
        form = Listform()
    lists = List.objects.filter(user=request.user).order_by("-updated_at")
    return render(request, "lists/index.html", {
        "form": form,
        "lists": lists,
    })

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item list login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
</head>
<body>
    <h1 class="login-title">ログイン画面</h1>

    {% if form.errors %}
       <p class="login-error-message">
            ユーザー名またはパスワードが正しくありません
       </p>
    {% endif %}
    <form method="post">
        {% csrf_token %}

        <div>
            <label for="id_username">ユーザー名</label><br>
            <input 
                type="text"
                name="username"
                id="id_username"
                required
            >
        </div>
        <div>
            <label for="id_password">パスワード</label><br>
            <input 
                type="password"
                name="password"
                id="id_password"
                required
            >
        </div>
        <button type="submit" class="login-button">ログイン</button>
        <p class="register-link">
            アカウントをお持ちでない方は
            <a href="{% url 'accounts:register' %}">こちら</a>
        </p>
    </form>
    
</body>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account register</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
</head>
<body>
    <h1 class="register-title">アカウント登録画面</h1>

    <form method="post" action="">
        {% csrf_token %}
        <div class="register-form-group">
            <label for="id_username">ユーザー名</label>
            <input type="text" name="username" value="{{ username|default:'' }}" id="id_username" autocomplete="username">
            <p class="help-text">※１～２０文字</p>

            {% if errors.username %}
                <ul class="register-error-message">
                    {% for error in errors.username %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="register-form-group">
            <label for="id_email">メールアドレス</label>
            <input type="email" name="email" value="{{ email|default:'' }}" id="id_email" autocomplete="email">
            <p class="help-text">※〇〇＠〇〇.〇〇</p>

            {% if errors.email %}
                <ul class="register-error-message">
                    {% for error in errors.email %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="register-form-group">
            <label for="id_password1">パスワード</label>
            <input type="password" name="password1" id="id_password1" autocomplete="new-password">
            <p class="help-text">※８文字以上＋英字と数字を両方含める</p>

            {% if errors.password1 %}
                <ul class="register-error-message">
                    {% for error in errors.password1 %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="register-form-group">
            <label for="id_password2">確認用パスワード</label>
            <input type="password" name="password2" id="id_password2" autocomplete="new-password">
            <p class="help-text">※再度同じパスワードを入力</p>

            {% if errors.password2 %}
                <ul class="register-error-message">
                    {% for error in errors.password2 %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <button type="submit" class="register-button">アカウント登録</button>
    </form>
    
</body>
</html>

lists/templates/lists/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lists index</title>
</head>
<body>
    
</body>
</html>